spring:
  application:
    name: sites-services
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sitesdb?createDatabaseIfNotExist=true
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:1305/eureka/

# Keycloak
keycloak:
  realm: spring
  baseUrl: http://localhost:8087
  username: admin
  password: 221Jamono2.0
  grant-type: password
  tokenUrl: http://localhost:8087/realms/spring/protocol/openid-connect/token
  introspection-uri: http://localhost:8087/realms/spring/protocol/openid-connect/token/introspect
  client-secret: ir3qrDh9I5kKLU3qJaC4LfKkhL2at0Ec
  client-id: gaydelID
  logout-url: http://localhost:8087/realms/spring/protocol/openid-connect/logout

# jwt
jwt:
  jwk-set-uri: http://localhost:8087/realms/spring/protocol/openid-connect/certs
  token:
    converter:
      principal-attribute: preferred_username


server:
  port: 1309
