spring:
  application:
    name: auth-services

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:1305/eureka/

# Keycloak
keycloak:
  realm: spring
  baseUrl: http://localhost:8087
  username: admin
  password: 221Jamono2.0
  grant-type: password
  tokenUrl: http://localhost:8087/realms/spring/protocol/openid-connect/token
  introspection-uri: http://localhost:8087/realms/spring/protocol/openid-connect/token/introspect
  client-secret: eQrSh8y3CY7BHUbjREwRNJHI1BfW5a53
  client-id: gaydelID
  logout-url: http://localhost:8087/realms/spring/protocol/openid-connect/logout

# jwt
jwt:
  jwk-set-uri: http://localhost:8087/realms/spring/protocol/openid-connect/certs
  token:
    converter:
      principal-attribute: preferred_username

server:
  port: 1313